### PR TITLE
Header Enhancements

### PR DESCRIPTION
**Pull request by rbvea**
- [x] Header styling is grey
- [x] Edit icon shows up on logo hover
- [x] Edit icon clicks toggles header tray
- [x] Clicking on 'update logo' allows user to update logo
- [x] Logo persists on refresh

Pivotal story: https://www.pivotaltracker.com/story/show/114058487

### CODE REVIEW

**Comment by rbvea** [comment]
@tommyokeefe this should be good to go

**Comment by tommyokeefe** [comment]
@rbvea If I don't get to this tonight I'll hit it tomorrow morning.

**Comment by tommyokeefe** [comment]
I was having some problems with the logo and realized it was from when I imported the DB from pantheon... my site is at brandcenter.app. oops! Everything is working great and the code looks good. I think it would be good to talk about autoloading and psr-0 vs psr-4 cost/benefit, but we can probably do that in the style guide repo rather than here. Are you enjoying Vue as your working with it more? Is vuex helpful or does it too much for this project?

**Comment by tommyokeefe** [comment]
If it wasn't clear, this is good to merge. :+1: :smile:

**Comment by rbvea** [comment]
Thanks for confirming.  I'm liking Vue except you pretty much have to build things from scratch, since the Vue ecosystem is smaller than Angular/React.

Vuex is great since it's a great way to separate code.  Most of the files I have are more than a couple of hundred lines longs (and not too wide either). I do wish there was an easier way to bind actions to the component (like how redux has a @bindToProps decorator) but that could probably done later.  For me it's not too overkill since the app is supposed to be super-flexible so having a state that's outside the app makes easier to work with.

**Comment by rbvea** [comment]
Some other things I noticed here though:

* No tests
* Probably should just default the home route to the one page we have now
* Some incomplete documentation

**Pull request merged**
