### PR TITLE
Brand item

### PR DESCRIPTION
**Pull request by rbvea**
# BrandItem CRUD
- [x] User should be able to add Brand Item to a section
- [x] user should be able to see list of associated Brand Items for each section
- [x] User should be able to delete Brand Item from a section
- [x] User should be able to edit type of Brand Item

Pivotal story: https://www.pivotaltracker.com/story/show/113207401

# Image upload component

- [x] User should be able to upload image to photo module
- [x] User should view uploaded image on photo module
- [x] User should be able to update image on photo module

Pivotal story: https://www.pivotaltracker.com/story/show/113119165

# Wysiwyg component
- [x] User should be able to set module type as 'Rich Text'
- [x] User should see wysiwyg if moule type is 'Rich Text'
- [x] User should be able to edit and save rich text element

Pivotal story: https://www.pivotaltracker.com/story/show/113206339

# Color Picker component
- [x] Brand Item Color type should be selectable
- [x] Image picker should appear when item.edit = true
- [x] Image picker should change div background-color dynamically
- [x] Saving item should update frontend
- [x] Saving item should persist upon refresh

Pivotal story: https://www.pivotaltracker.com/story/show/113206707

### CODE REVIEW

**Comment by rbvea** [comment]
Production updated: http://dev-wordpress-boilerplate.pantheon.io/brand-center/

**Comment by rbvea** [comment]
Added an image upload componennt

**Comment by rbvea** [comment]
Pushed a bunch of stuff that's related to this PR to `flexbox` (pr #3)

# Fixed 'Cannot delete section due to foreign constraints.' error
- [ ] Deleting sections with related item should delete related items
https://www.pivotaltracker.com/story/show/113597141

# Unable to edit item after intial creation
- [ ] Item should be editable right after creation
https://www.pivotaltracker.com/story/show/113596147

**Comment by tommyokeefe** [comment]
Looks good! :+1:

**Comment by tommyokeefe** [comment]
If I add a section I can't edit it until after a refresh.

**Comment by tommyokeefe** [comment]
To clarify, I can't add an item to it until after a refresh

**Comment by tommyokeefe** [comment]
Looks like it's happening at line 25 of `BrandItem.js` - ```Object.assign(section, {items: section.items.concat([saved_item])})```

The error I get is: `Uncaught TypeError: Cannot read property 'concat' of undefined`

**Pull request merged**
