### PR TITLE
Brand Item Enhancements

### PR DESCRIPTION
**Pull request by rbvea**
# Flexbox grid
- [x]  Grid should be now flexbox-based
- [x]  Grid should work in non-flexbox-supported browsers with a polyfill

Pivotal story: https://www.pivotaltracker.com/story/show/113596399

# BrandItem outline

- [x] Items should only be outlined when in 'edit' mode

Pivotal story: https://www.pivotaltracker.com/story/show/113673317

# Bugs

- [x] Brand Item unable to be created after Section is created (needs refresh)
- [x] IE11 bug

### CODE REVIEW

**Comment by rbvea** [comment]
@tommyokeefe this should be good to go

**Comment by tommyokeefe** [comment]
Is this branch up on the review app yet?

**Comment by rbvea** [comment]
Yes it's up on the review app.

**Comment by tommyokeefe** [comment]
Sweet

**Comment by tommyokeefe** [comment]
I've tried to get this running in vagrant as a plugin on a wordpress install, but I keep running into the same problem:
I navigate to `/brand-center/` and it initially looks like it's working correctly. I get the `#!` appended to the url and the loading dots pop up, but it never loads. In the console I have a warning and two errors:

`vue-router.js:728 [vue-router] <router-view> can only be used inside a router-enabled app.`
`(index):1 Uncaught (in promise) SyntaxError: Unexpected token <`
`(index):1 Uncaught (in promise) SyntaxError: Unexpected token <`

Any idea what might be missing?

**Comment by tommyokeefe** [comment]
Trying to test the Flew polyfill I ran into IE11 errors:

`[vue-router] <router-view> can only be used inside a router-enabled app.`
`[Vue warn]: Error when evaluating expression "page.name". Turn on debug mode to see stack trace.`
`[Vue warn]: Invalid expression. Generated function body:  ['item',`scope.item--scope.${scope.item.type}`,scope.item.edit?'item--active':'']`
`[Vue warn]: Error when evaluating expression "['item', `item--${item.type}`, item.edit ? 'item--active': '']".`
`SCRIPT5007: Unable to get property 'call' of undefined or null reference
vue.common.js (983,1)`

**Comment by rbvea** [comment]
@tommyokeefe re: https://github.com/AtlanticMediaStrategies/brand-center-plugin/pull/3#issuecomment-185304861

Any errors in the php logs?

**Comment by rbvea** [comment]
Also I'm assuming you cloned from pantheon?

**Comment by rbvea** [comment]
@tommyokeefe can you provide what the response was that triggered the error?

**Comment by tommyokeefe** [comment]
@rbvea Sorry man, got pulled away and then had to head home. I'm online again for a bit. I hadn't cloned from Pantheon, I just started with a clean wordpress install. Let me try cloning and see what results I get. I was figuring since it's a plugin I would test it on a clean install. Let me try it with your stuff from Pantheon.

**Comment by rbvea** [comment]
@tommyokeefe I thought I had clarified that you need to clone the prod db, but yeah I need to make some tasks to create the db structure on activate/deactivate.

**Comment by tommyokeefe** [comment]
@rbvea You probably did say that last week and I just forgot. I just looked at the response and that's definitely the problem, it's trying to select form a table that doesn't exist.

**Comment by tommyokeefe** [comment]
@rbvea Just wanted to circle back and let you know that I have this running locally, so any future PR's should be easier to check. Once Nguyet and I get tomorrow night's refresh talk behind us I should be much quicker to respond.

**Comment by rbvea** [comment]
Thanks Tommy, I'm working on those bugs so I'll ping you when they should be
resolved.

> On Feb 17 2016, at 3:10 pm, tommyokeefe &lt;notifications@github.com&gt;
wrote:  

>

> [@rbvea](https://github.com/rbvea) Just wanted to circle back and let you
know that I have this running locally, so any future PR's should be easier to
check. Once Nguyet and I get tomorrow night's refresh talk behind us I should
be much quicker to respond.

>

> —  
Reply to this email directly or [view it on
GitHub](https://github.com/AtlanticMediaStrategies/brand-center-plugin/pull/3#
issuecomment-185491231).

**Comment by rbvea** [comment]
@tommyokeefe the two bugs in the description should be fixed now

**Comment by tommyokeefe** [comment]
Sweet. I'll check first thing tomorrow!

**Comment by tommyokeefe** [comment]
Everything looks great and is working fine. The tests look good as well :+1:

**Comment by rbvea** [comment]
Thanks @tommyokeefe, will merge this in

**Pull request merged**
