### PR TITLE
Brand section CRUD

### PR DESCRIPTION
**Pull request by rbvea**
- [x] User is able to create a section
- [x] User sees an updated list of sections once created
- [x] User is able to update a section once created
- [x] User is able to delete a section

### CODE REVIEW

**Comment by nateluzod** [comment]
@rbvea to verify functionality I should just make a blank install and run this plugin? Anything else?

**Comment by rbvea** [comment]
Updated production with latest app: http://dev-wordpress-boilerplate.pantheon.io/brand-center/#!/

**Comment by rbvea** [comment]
@nateluzod sorry for the late reply, need sync db's but after that it should to test

**Comment by rbvea** [comment]
Also feel free to leave any comments about the app structure, you too @tommyokeefe

**Comment by tommyokeefe** [comment]
OK. Coming back to this now. Here's to hoping I won't get interrupted! :smile:

**Comment by tommyokeefe** [comment]
@rbvea Have you found it helpful using the Wordpress plugin boilerplate? I like the structure it provides. Digging through your code now to get an idea of how it works. so far I really like it :+1:

**Comment by rbvea** [comment]
@tommyokeefe the wordpress plugin boilerplate is sorta helpful, though I'm just using the loader class.  Thanks for reviewing this, will merge this in once #2 and #3 are merged in as well.

**Comment by tommyokeefe** [comment]
This all looks good. I really like the overall structure of the code. It's easy to understand what's going on!

Feel free to merge it. :+1: I'll look at the other PR's now.

**Pull request merged**
